In [1]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001,size=(1000,20))

# print the shape of X
X.shape


(1000, 20)

In [2]:
ave_cols=np.mean(X,axis=0)
ave_cols

array([2530.792, 2511.817, 2468.152, 2570.864, 2510.546, 2596.59 ,
       2563.766, 2523.769, 2450.35 , 2521.893, 2519.251, 2489.42 ,
       2453.977, 2536.217, 2480.668, 2431.212, 2485.439, 2477.785,
       2466.443, 2451.556])

In [3]:
# Standard Deviation of the values in each column of X
std_cols =np.std(X,axis=0)
std_cols

array([1485.07674709, 1425.28453774, 1463.73506786, 1445.23308207,
       1489.58334036, 1464.88352981, 1475.05170731, 1445.47537151,
       1457.73359483, 1417.19859566, 1464.98525317, 1476.60621955,
       1454.09373304, 1454.99942334, 1430.48519733, 1457.15821415,
       1413.66092055, 1479.0229771 , 1425.63389647, 1458.18703562])

In [4]:
# Print the shape of ave_cols

print(ave_cols.shape)

print(std_cols.shape)

# Print the shape of std_cols


(20,)
(20,)


In [5]:
# Mean normalize X
X_norm =X-ave_cols
X_norm

array([[ 1409.208, -1764.817,   563.848, ...,   218.215, -2087.443,
         1565.444],
       [-1368.792,  2125.183,   489.848, ..., -1045.785, -1220.443,
         1827.444],
       [ 2024.208,  -774.817,  -880.152, ..., -2317.785,   292.557,
          292.444],
       ...,
       [ 2253.208,  -562.817, -1709.152, ...,  -550.785,   740.557,
          230.444],
       [ 1166.208,   326.183, -1391.152, ...,   -45.785,  1912.557,
        -1171.556],
       [  426.208, -1814.817, -1448.152, ...,  2096.215,  1605.557,
          270.444]])

In [6]:
# Print the average of all the values of X_norm

avg_Xnorm=np.mean(X_norm,axis=0)
avg_Xnorm



# Print the average of the maximum value in each column of X_norm


array([-1.99634087e-13,  1.80079951e-13, -5.49334800e-13, -8.55834514e-13,
       -1.55978341e-13,  1.89174898e-13, -6.48924470e-13, -2.08729034e-13,
        1.02772901e-13, -2.91038305e-14, -4.00177669e-13,  5.09317033e-13,
        7.12134351e-13, -3.63797881e-13, -2.99678504e-13,  4.31555236e-13,
        4.17003321e-13,  9.45874490e-14,  5.80257620e-13, -2.72848411e-13])

In [7]:
min_values_along_columns = np.min(X_norm, axis=0)
min_values_along_columns


array([-2530.792, -2509.817, -2468.152, -2567.864, -2508.546, -2591.59 ,
       -2561.766, -2520.769, -2449.35 , -2516.893, -2519.251, -2487.42 ,
       -2450.977, -2535.217, -2476.668, -2428.212, -2475.439, -2475.785,
       -2465.443, -2450.556])

In [8]:
avg_min=np.mean(min_values_along_columns)
avg_min

-2499.52535

In [9]:
max_values_along_columns = np.max(X_norm, axis=0)
max_values_along_columns
avg_max=np.mean(max_values_along_columns)
avg_max

2493.22465

In [10]:
shape=X_norm.shape
print(shape)
y=1000
row_indices=np.random.permutation(y)
row_indices

(1000, 20)


array([786, 397, 130, 833, 417,  22, 775, 266, 980, 471, 339, 341, 708,
       253, 279, 314, 121, 172, 884, 816, 416,  87, 515, 909, 102, 146,
       637, 891, 542, 935, 986,  17, 679, 819, 511, 271, 912, 846, 315,
       906, 402, 824, 357, 967,  54, 939, 748, 470, 596,  80, 560, 346,
        11, 449, 796, 701, 689, 372, 779, 330, 499, 335, 830, 839,  44,
       882, 678, 687, 506, 597, 871, 246, 918, 440, 730, 888, 954, 414,
       373, 836, 649, 998, 124,   9, 289, 995, 476, 584, 311, 651, 996,
       746, 458, 435, 801, 916,  75, 941, 570, 390, 732, 791, 634, 834,
       282, 203,  50, 602, 110, 211, 516, 285, 396,  69, 933, 612, 759,
       348, 389, 948, 529, 692, 874, 664, 992, 387, 192, 363, 507, 181,
        83, 325, 138,  10, 642, 859, 758, 400, 362, 724, 215, 179,  84,
       198, 690, 352, 710, 309,  90, 139, 257,  51, 237, 381, 953, 454,
       394, 473, 971, 302, 897, 290, 919, 847, 556, 184, 982, 509, 573,
       867, 592, 551,  19, 643, 268, 291, 359, 623, 272,  56, 72

In [11]:
X_train =X[row_indices[0:600]]
X_train.shape
# Create a Cross Validation Set
X_crossVal =X[row_indices[600:800]]

# # Create a Test Set
X_test =X[row_indices[800:1000]]

In [12]:
# Print the shape of X_train
X_train.shape

# Print the shape of X_crossVal
X_crossVal.shape


# Print the shape of X_test
X_test.shape


(200, 20)